load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_cc//cc:defs.bzl", "cc_test")

cc_library(
    name = "test_base",
    hdrs = ["test_base.h",],
    visibility = ["//visibility:public"],
)

TEST_DEPS = [
    "@googletest//:gtest",
    "@googletest//:gtest_main",
]

cc_test(
    name = "util",
    srcs = ["util.cpp"],
    deps = TEST_DEPS + [
        "//src/emulator:util",
    ],
)

cc_test(
    name = "main",
    srcs = ["main.cpp"],
    deps = TEST_DEPS + [],
)

cc_test(
    name = "memory", 
    srcs = ["memory.cpp"],
    deps = TEST_DEPS + [
        "//src/emulator:memory",
    ],
)

cc_test(
    name = "registers",
    srcs = ["registers.cpp"],
    deps = TEST_DEPS + [
        "//src/emulator:registers",
    ],
)

cc_test(
    name = "CPU",
    srcs = ["CPU.cpp"],
    deps = TEST_DEPS + [
        "//src/emulator:CPU",
    ]
)
