load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "main",
    srcs = ["main.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "memory", 
    srcs = ["memory.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//src/emulator:memory",
    ],
)

cc_test(
    name = "registers",
    srcs = ["registers.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//src/emulator:registers",
    ],
)

cc_test(
    name = "CPU",
    srcs = ["CPU.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//src/emulator:CPU",
    ]
)

cc_test(
    name = "op",
    srcs = ["op.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//src/emulator:op",
    ]
)