load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "main",
    srcs = ["main.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "memory", 
    srcs = ["memory.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//src/cpu:memory",
    ],
)