load("@rules_cc//cc:defs.bzl", "cc_test")

TEST_DEPS = [
    "//src/emulator:CPU",
    "//src/emulator:memory",
    "@googletest//:gtest",
    "@googletest//:gtest_main",
]

cc_test(
    name = "decoder",
    srcs = ["decoder.cpp"],
    deps = TEST_DEPS + [
        "//src/emulator/op:decoder",
    ]
)

cc_test(
    name = "ld",
    srcs = ["ld.cpp"],
    deps = TEST_DEPS + [
        "//src/emulator/op:ld",
    ]
)

cc_test(
    name = "nop",
    srcs = ["nop.cpp"],
    deps = TEST_DEPS + [
        "//src/emulator/op:nop",
    ]
)

cc_test(
    name = "add",
    srcs = ["add.cpp"],
    deps = TEST_DEPS + [
        "//src/emulator/op:add",
    ],
)

cc_test(
    name = "bit",
    srcs = ["bit.cpp"],
    deps = TEST_DEPS + [
        "//src/emulator/op:bit",
    ],
)

cc_test(
    name = "stack",
    srcs = ["stack.cpp"],
    deps = TEST_DEPS + [
        "//src/emulator/op:stack",
    ],
)

cc_test(
    name = "sub",
    srcs = ["sub.cpp"],
    deps = TEST_DEPS + [
        "//src/emulator/op:sub",
    ],
)
