load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "util",
    #srcs = ["util.cpp"],
    hdrs = ["util.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "memory",
    srcs = ["memory.cpp"],
    hdrs = ["memory.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "registers",
    #srcs = ["registers.cpp"],
    hdrs = ["registers.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "CPU", 
    srcs = ["CPU.cpp"],
    hdrs = ["CPU.h"],
    deps = [
        ":memory",
        ":registers",
        ":util",
        "//src/emulator/op:op",
    ],
    visibility = ["//visibility:public"],
)
